976 convert start pages to generate markdown
GSA/notifications-admin pull request #1052
Opened 2023-12-22 17:09 UTC by anagradova

convert_markdown_template in formatters.py accepts a markdown file name string, will read the ".md" markdown file from the 'app/content' directory and return an HTML string for rendering. The md file can contain markdown, HTML, and jinja2 tags. The processing pipeline renders markdown first and then tags.

2024-01-03 16:46 UTC, stvnrlly requested changes
The Python part looks like it should do exactly what we're looking for 👍🏻 . I left some feedback about the Markdown parts.

2024-01-03 16:46 UTC, stvnrlly commented on app/content/get-started.md
> +    <p>You should <a class="usa-link" href="{{ url_for('.request_to_go_live', service_id=current_service.id) }}">request to go live</a> when you’re ready to send messages to people outside your team.
```suggestion
    <p>You should <a class="usa-link" href="{{ url_for('.support') }}">request to go live</a> when you’re ready to send messages to people outside your team. We’ll approve your request within one working day.</p>
```

I recently changed https://github.com/GSA/notifications-admin/blob/main/app/templates/views/get-started.html, so the `request_to_go_live` route no longer exists. This should fix the current build error.

2024-01-03 16:46 UTC, stvnrlly commented on app/content/get-started.md
HTML is valid Markdown, but for our purposes we'd like to have this file be non-HTML Markdown. That'll hopefully make it easier for non-developers to edit this.

For example, the first line here should be 
```
# Get started
```

2024-01-03 17:11 UTC, anagradova commented on app/content/get-started.md
Would you like me to modify the md file to only use markdown (where possible)? I assume we'll keep the jinja template tags in the markdown file?

2024-01-03 17:56 UTC, stvnrlly commented on app/content/get-started.md
Yes, please! I am assuming that Jinja tags will still work, but I have not tried it myself to confirm that.

2024-01-03 18:41 UTC, anagradova commented on app/content/get-started.md
They will work. It passes through the markdown conversion first so the template will look normal (tags + HTML) to the render_template_string method.

2024-01-09 15:23 UTC, ccostino commented
@anagradova I think we're good to go here!  We just need one more update against `main` as a few other dependency updates had gone in and I want to make sure the Poetry files are in good shape. :-) Thanks!

2024-01-09 16:13 UTC, ccostino approved these changes
Thanks, @anagradova!

2024-01-09 16:27 UTC, stvnrlly approved these changes

2024-01-09 16:27 UTC, merged