Add latest version commit hash to footer (notify-admin-204)
GSA/notifications-admin pull request #1245
Opened 2024-02-26 19:11 UTC by terrazoon

*A note to PR reviewers: it may be helpful to review our
[code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews)
to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a clear description about your proposed changes and what the
expected outcome(s) is/are from there.  If there are complex implementation
details within the changes, this is a great place to explain those details using
plain language.

This should include:

- Links to issues that this PR addresses
- Screenshots or screen captures of any visible changes, especially for UI work
- Dependency changes

If there are any caveats, known issues, follow-up items, etc., make a quick note
of them here as well, though more details are probably warranted in the issue
itself in this case.

## TODO (optional)

If you're opening a draft PR, it might be helpful to list any outstanding work,
especially if you're asking folks to take a look before it's ready for full
review.  In this case, create a small checklist with the outstanding items:

- [ ] TODO item 1
- [ ] TODO item 2
- [ ] TODO item ...

## Security Considerations

Please think about the security compliance aspect of your changes and what the
potential impacts might be.

**NOTE:  Please be mindful of sharing sensitive information here!  If you're not
sure of what to write, please ask the team first before writing anything here.**

Relevant details could include (and are not limited to) the following:

- Handling secrets/credential management (or specifically calling out that there
  is nothing to handle)
- Any adjustments to the flow of data in and out the system, or even within it
- Connecting or disconnecting any external services to the application
- Handling of any sensitive information, such as PII
- Handling of information within log statements or other application monitoring
  services/hooks
- The inclusion of a new external dependency or the removal of an existing one
- ... (anything else relevant from a security compliance perspective)

There are some cases where there are no security considerations to be had, e.g.,
updating our documentation with publicly available information.  In those cases
it is fine to simply put something like this:

- None; this is a documentation update with publicly available information.

2024-03-11 17:34 UTC, ccostino requested changes
Thanks, @terrazoon!  All looks good to me here, I have just one minor request for adjusting what we display in the case of noting having a commit hash available - suggestion already given! :-)

Speaking of which, I can't think of any situation where that wouldn't come through unless the `git` command failed for some reason, but even in that scenario I suspect that other failures would be taking place as well.  Is there any situation you can think of where just that command would fail and if so, is there a fallback we need in the script to account for it so the whole thing doesn't fail?

2024-03-11 17:34 UTC, ccostino commented on app/config.py
> +    COMMIT_HASH = getenv("COMMIT_HASH", "Unknown")
Let's change `Unknown` to several dashes instead:

```suggestion
    COMMIT_HASH = getenv("COMMIT_HASH", "-----")
```

2024-03-13 17:18 UTC, terrazoon commented
> Thanks, @terrazoon! All looks good to me here, I have just one minor request for adjusting what we display in the case of noting having a commit hash available - suggestion already given! :-)
> 
> Speaking of which, I can't think of any situation where that wouldn't come through unless the `git` command failed for some reason, but even in that scenario I suspect that other failures would be taking place as well. Is there any situation you can think of where just that command would fail and if so, is there a fallback we need in the script to account for it so the whole thing doesn't fail?

I think the dashes are enough.  Obviously we don't want it to fail so if we see dashes on staging, will have to debug there.

2024-03-14 16:13 UTC, ccostino approved these changes
Thanks, @terrazoon!

2024-03-14 16:13 UTC, merged