974 - Content updates on Pricing and Guidance pages
GSA/notifications-admin pull request #1257
Opened 2024-02-28 21:12 UTC by jonathanbobel

*A note to PR reviewers: it may be helpful to review our
[code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews)
to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a clear description about your proposed changes and what the
expected outcome(s) is/are from there.  If there are complex implementation
details within the changes, this is a great place to explain those details using
plain language.

This should include:

- Links to issues that this PR addresses
- Screenshots or screen captures of any visible changes, especially for UI work
- Dependency changes

If there are any caveats, known issues, follow-up items, etc., make a quick note
of them here as well, though more details are probably warranted in the issue
itself in this case.

## TODO (optional)

If you're opening a draft PR, it might be helpful to list any outstanding work,
especially if you're asking folks to take a look before it's ready for full
review.  In this case, create a small checklist with the outstanding items:

- [ ] TODO item 1
- [ ] TODO item 2
- [ ] TODO item ...

## Security Considerations

Please think about the security compliance aspect of your changes and what the
potential impacts might be.

**NOTE:  Please be mindful of sharing sensitive information here!  If you're not
sure of what to write, please ask the team first before writing anything here.**

Relevant details could include (and are not limited to) the following:

- Handling secrets/credential management (or specifically calling out that there
  is nothing to handle)
- Any adjustments to the flow of data in and out the system, or even within it
- Connecting or disconnecting any external services to the application
- Handling of any sensitive information, such as PII
- Handling of information within log statements or other application monitoring
  services/hooks
- The inclusion of a new external dependency or the removal of an existing one
- ... (anything else relevant from a security compliance perspective)

There are some cases where there are no security considerations to be had, e.g.,
updating our documentation with publicly available information.  In those cases
it is fine to simply put something like this:

- None; this is a documentation update with publicly available information.

2024-02-28 21:32 UTC, stvnrlly reviewed
👍🏻 on implementation, a couple specific questions for @maomeara63

2024-03-08 18:08 UTC, terrazoon commented on app/templates/views/guidance/index.html
> -    <li>Click “<a href={{ url_for('.choose_template', service_id=current_service.id) }}>Send Messages</a>”. You’ll see existing templates.</li>
heheh smart quotes.

2024-03-08 18:09 UTC, terrazoon commented on app/templates/views/guidance/index.html
>    <p class="padding-2 bg-base-lightest">State WIC: Hello ((first name)), your reference is ((ref number)). Please provide this number when you call 123-123-1234 to make an appointment.</p>
I don't know if 123 is a legit area code, but should we do '555' to guarantee the invalidity of the number?

2024-03-08 18:09 UTC, terrazoon commented on app/templates/views/guidance/index.html
>    <p class="padding-2 bg-base-lightest">State WIC: Hello ((first name)), your reference is ((ref number)). Please provide this number when you call 123-123-1234 to make an appointment.</p>
123-555-1234 or 123-555-5555 or 555-555-5555 etc.

2024-03-08 21:56 UTC, ccostino requested changes
Thanks, @jonathanbobel!

Let's remove the remaining smart quotes and see if we can fix the phone number quick while we're at it - hopefully the suggestions make it simple to do right here!

2024-03-08 21:56 UTC, ccostino commented on app/templates/views/guidance/index.html
> +    <li>Click “<a href={{ url_for('.choose_template', service_id=current_service.id) }}>Send Messages</a>”. You'll see existing templates.</li>
Ah, the smart quotes persist here!  Let's get those fixed:

```suggestion
    <li>Click "<a href={{ url_for('.choose_template', service_id=current_service.id) }}>Send Messages</a>". You'll see existing templates.</li>
```

2024-03-08 21:56 UTC, ccostino commented on app/templates/views/guidance/index.html
>    <p class="padding-2 bg-base-lightest">State WIC: Hello ((first name)), your reference is ((ref number)). Please provide this number when you call 123-123-1234 to make an appointment.</p>
I think we can just make a suggestion here even though this isn't changed code.  Let's try!

```suggestion
  <p class="padding-2 bg-base-lightest">State WIC: Hello ((first name)), your reference is ((ref number)). Please provide this number when you call 555-555-5555 to make an appointment.</p>
```

2024-03-13 18:29 UTC, ccostino approved these changes
Thanks, @jonathanbobel!

2024-03-13 18:29 UTC, merged