805 make dashboard links clickable
GSA/notifications-admin pull request #1326
Opened 2024-03-19 16:27 UTC by jonathanbobel

## Description

The dashboard had a large clickable area that didn't look like an actual link or button that allowed the user to drill down into a Status page for their recent messages. This fix removed those areas and created one single "Details" button that is more self-explanatory and allows for the same functionality. 

Additionally, I removed the section that showed failures (and the subsequent confusing link to _just_ the failures section). The user can still click on the Details button and see the combined status page, including failures. 

Upcoming designs will have data visualizations to better show the Status - all current Delivered/Pending/Failed.

2024-03-19 20:22 UTC, terrazoon approved these changes
LGTM

2024-03-19 22:12 UTC, heyitsmebev requested changes
I like the use of an actual button! 

One styling observation:  It seems like the font size was carried over from the original version with the blue box. Now, without the blue box, the font appears significantly larger in comparison to the rest. I'm curious if this was intentional. If it was, just disregard this comment. If not, I think you could bring it down .5rem or so to help it look more balanced 
![image](https://github.com/GSA/notifications-admin/assets/53159604/b9b3556f-00ed-41e3-8a21-2dfb7e07d797)

2024-03-19 22:12 UTC, heyitsmebev commented on app/templates/views/dashboard/_totals.html
> +        <p>
this p tag could be deleted. It's creating this large gap between the number and "Messages sent"
![image](https://github.com/GSA/notifications-admin/assets/53159604/bb57fc15-a4d3-4e49-8f6b-d1c42ffe92d5)

2024-04-01 17:46 UTC, heyitsmebev approved these changes
✅

2024-04-03 23:03 UTC, ccostino approved these changes
Thanks, @jonathanbobel!

2024-04-03 23:03 UTC, merged