1484 dashboard visualizations
GSA/notifications-admin pull request #1623
Opened 2024-06-18 12:28 UTC by jonathanbobel

*A note to PR reviewers: it may be helpful to review our
[code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews)
to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a clear description about your proposed changes and what the
expected outcome(s) is/are from there.  If there are complex implementation
details within the changes, this is a great place to explain those details using
plain language.

This should include:

- Links to issues that this PR addresses
- Screenshots or screen captures of any visible changes, especially for UI work
- Dependency changes

If there are any caveats, known issues, follow-up items, etc., make a quick note
of them here as well, though more details are probably warranted in the issue
itself in this case.

## TODO (optional)

If you're opening a draft PR, it might be helpful to list any outstanding work,
especially if you're asking folks to take a look before it's ready for full
review.  In this case, create a small checklist with the outstanding items:

- [ ] TODO item 1
- [ ] TODO item 2
- [ ] TODO item ...

## Security Considerations

Please think about the security compliance aspect of your changes and what the
potential impacts might be.

**NOTE:  Please be mindful of sharing sensitive information here!  If you're not
sure of what to write, please ask the team first before writing anything here.**

Relevant details could include (and are not limited to) the following:

- Handling secrets/credential management (or specifically calling out that there
  is nothing to handle)
- Any adjustments to the flow of data in and out the system, or even within it
- Connecting or disconnecting any external services to the application
- Handling of any sensitive information, such as PII
- Handling of information within log statements or other application monitoring
  services/hooks
- The inclusion of a new external dependency or the removal of an existing one
- ... (anything else relevant from a security compliance perspective)

There are some cases where there are no security considerations to be had, e.g.,
updating our documentation with publicly available information.  In those cases
it is fine to simply put something like this:

- None; this is a documentation update with publicly available information.

2024-07-02 23:23 UTC, heyitsmebev commented on app/templates/old/admin_template.html
> +  <script type="text/javascript" src="{{ asset_url('js/chart.js') }}"></script>
we wont need this here

2024-07-23 06:30 UTC, heyitsmebev commented on app/assets/js/chart.js
Do we need this?

2024-07-23 06:38 UTC, heyitsmebev commented on app/templates/views/dashboard/dashboard.html
> +        <div class="chart-container" id="weeklyChart" data-service-id="{{ service_id }}"></div>
do we need to pass the service_id?

2024-07-23 13:36 UTC, jonathanbobel commented on app/assets/js/chart.js
we do not, removing

2024-07-24 15:16 UTC, terrazoon approved these changes
I think when I used d3 more than 5 years ago, I just grabbed some google examples for pie charts and bar charts and made them into reusable classes, but for the tables that was just plain html and not part of d3.

I defer to you on this because I see you are making these tables accessible, etc.

2024-07-25 06:04 UTC, heyitsmebev requested changes
Good job with all the javascript and js testing! I can tell a lot of hard work was put into this! I left a couple small feedbacks, otherwise LGTM

2024-07-25 06:04 UTC, heyitsmebev commented on app/templates/views/dashboard/dashboard.html
> +    {#  <h2 class="margin-top-4 margin-bottom-1">Message count</h2>
Same here, could we delete if we are planning to comment out?

2024-07-25 06:04 UTC, heyitsmebev commented on gulpfile.js
> +  templates: 'app/templates/',
you might have a merge conflict here. I believe Alex removed this line

2024-07-25 06:06 UTC, heyitsmebev commented on app/assets/javascripts/activityChart.js
> +            const userId = ctx.getAttribute('data-service-id'); // Assuming user ID is the same as service ID
const userId = ctx.getAttribute('data-service-id');

2024-08-01 22:46 UTC, heyitsmebev approved these changes
LGTM

2024-08-01 22:47 UTC, heyitsmebev commented on gulpfile.js
> +  templates: 'app/templates/',
I removed the extra line and synced with main in order for this PR to get merged today

2024-08-02 01:31 UTC, ccostino approved these changes
Thank you, @jonathanbobel! 🎉 

(and thank you @heyitsmebev for the quick assist with the final sync with `main`!)

There _might_ be a slight issue with the chart displaying messages over the last 7 days, I'm not seeing any show up despite sending some test ones, but I think it's better to get this foundation in and then fix/tweak what still needs to be done, rather than hold the whole thing up.

2024-08-02 01:31 UTC, merged