add github repos to footer
GSA/notifications-admin pull request #1733
Opened 2024-07-17 16:59 UTC by terrazoon

## Description

Add GitHub repos to footer.

## Security Considerations

N/A

2024-07-17 17:00 UTC, terrazoon commented
<img width="1728" alt="Screenshot 2024-07-17 at 8 57 25 AM" src="https://github.com/user-attachments/assets/de17ed07-f832-4df4-a14f-156d630d91e9">

2024-07-23 14:41 UTC, ccostino requested changes
Thanks, @terrazoon!  One small request to format the links in a list.

2024-07-23 14:41 UTC, ccostino commented on app/templates/new/components/footer.html
> +        <a href="https://github.com/gsa/notifications-api" class="usa-identifier__required-link">Notify.gov API repo</a>
Let's turn this into a bulleted list for better readability/formatting:

```suggestion
        <ul>
          <li><a href="https://github.com/gsa/notifications-admin" class="usa-identifier__required-link">Notify.gov Admin repo</a></li>
        <li><a href="https://github.com/gsa/notifications-api" class="usa-identifier__required-link">Notify.gov API repo</a></li>
      </ul>
```

2024-07-23 22:41 UTC, ccostino approved these changes
Thanks, @terrazoon!

2024-07-23 22:41 UTC, merged