E2e tests uncomment
GSA/notifications-admin pull request #1996
Opened 2024-10-04 22:15 UTC by terrazoon

*A note to PR reviewers: it may be helpful to review our [code review documentation](https://github.com/GSA/notifications-api/blob/main/docs/all.md#code-reviews) to know what to keep in mind while reviewing pull requests.*

## Description

Please enter a detailed description here.

## TODO (optional)

* [ ] TODO item 1
* [ ] TODO item 2
* [ ] TODO item ...

## Security Considerations

* Consideration 1
* Consideration 2
* Consideration ...

2024-10-09 15:16 UTC, stvnrlly requested changes
I see how this works, but I think we'll want to have a discussion about the risks of moving `VCAP_SERVICES` around before we try this approach.

2024-10-09 15:16 UTC, stvnrlly commented on app/models/user.py
> +        # current_app.logger.info(f"Logged out {self.id}")
I think we'll still want these log messages for non-e2e environments

2024-10-09 16:14 UTC, terrazoon commented on app/s3_client/__init__.py
> +    )
I think this was experimental trying to work around something.  It may not be necessary, will see if I can revert.

2024-10-09 16:15 UTC, terrazoon commented on manifest.yml
> +      VCAP_SERVICES: ((VCAP_SERVICES))
Probably unnecessary.  I was making a lot of experimental changes, stumbling towards the solution that ultimately worked.

2024-10-11 17:10 UTC, ccostino commented on app/s3_client/__init__.py
> +    )
Noting that this was indeed switched back, thanks!

2024-10-11 17:10 UTC, ccostino commented on notifications_utils/s3.py
> +    )
Same, this has been switched back.

2024-10-15 16:46 UTC, ccostino approved these changes
Thank you for all of the work with this, @terrazoon!  I have no further questions or concerns, @stvnrlly.

2024-10-15 16:52 UTC, stvnrlly approved these changes

2024-10-15 16:57 UTC, merged