Updating site to use USWDS styles
GSA/notifications-admin pull request #509
Opened 2023-05-12 18:56 UTC by jonathanbobel

- [x] Update header & footer
- [x] Update home page
- [x] Update content pages
- [x] Update fonts
- [ ] Update colors
- [x] Update templates
- [ ] Update sending flow

2023-05-31 12:14 UTC, tdlowden approved these changes
Looks solid so far.

2023-05-31 14:19 UTC, stvnrlly requested changes

2023-05-31 14:19 UTC, stvnrlly commented on tests/app/main/views/test_manage_users.py
> +    # )
Let's see if we can either update tests, remove them as obsolete, or add a comment explaining what the blocker is

2023-05-31 14:26 UTC, stvnrlly commented on app/templates/components/uk_components/footer/template.njk
> +        <p class="usa-identifier__identity-domain">usnotify.gov</p>
```suggestion
        <p class="usa-identifier__identity-domain">notify.gov</p>
```

2023-05-31 19:48 UTC, jonathanbobel commented on app/assets/sass/uswds/_uswds-theme-custom-styles.scss
> +   font-weight: bold !important;
Yes, this is temporary as I am supporting both style sheets for now

2023-06-01 16:00 UTC, jonathanbobel commented
@stvnrlly pretty sure I got all your requests, check them out when you have a minute

2023-06-05 20:55 UTC, stvnrlly approved these changes

2023-06-06 19:28 UTC, merged